CREATE TABLE [dbo].[Department](
[ID] [int] IDENTITY(1,1) NOT NULL,
[name] [nvarchar](32) NOT NULL,
[description] [nvarchar](255) NULL,
[pid] [int] NULL,
[Status] [int] NOT NULL,
[Managetype] [int] NOT NULL,
CONSTRAINT [PK_Department] PRIMARY KEY CLUSTERED
(
[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY],
CONSTRAINT [IX_Department] UNIQUE NONCLUSTERED
(
[pid] ASC,
[name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO
